### ISSUE TITLE
H2 support removed by mistake? #2467

### ISSUE THREAD

**Issue by Miuler** [flyway/flyway-sbt#43]
https://github.com/flyway/flyway/issues/2467

Which version and edition of Flyway are you using?
6.0.0

Which database are you using (type & version)?
H2

Which operating system are you using?
Linux

Exception:
Caused by: org.flywaydb.core.api.FlywayException: Unsupported Database: H2
at org.flywaydb.core.internal.database.DatabaseFactory.createDatabase(DatabaseFactory.java:226) ~[flyway-core-6.0.0.jar:?]
at org.flywaydb.core.internal.database.DatabaseFactory.createDatabase(DatabaseFactory.java:107) ~[flyway-core-6.0.0.jar:?]
at org.flywaydb.core.Flyway.execute(Flyway.java:472) ~[flyway-core-6.0.0.jar:?]
at org.flywaydb.core.Flyway.clean(Flyway.java:285) ~[flyway-core-6.0.0.jar:?]

=> Think the commit f9bd09b removed H2 support in DatabaseFactory.java by mistake.

**Comment by davidmweber** [comment]
Sounds like a flyway issue, not a plugin issue.
